### ISSUE TITLE
Review & refactor zen errors 

### ISSUE THREAD

**Issue by KGOH** [zen-lang/zen#21]
## Current state:
- some errors are difficult to understand what they mean and to what they relate to 
- errors are not strictly categorized

## Desired state:
- [ ] as a developer I want to see human readable error description, it's location and understand how to fix it
- [ ] as a developer I want to be able to differentiate between types of errors (i.e. data validation, schema validation, namespace reading, etc)
- [ ] as a user I want to see errors with my language localization

## TODO:
- [ ] list all possible errors produced by zen
- [ ] design solution
- [ ] decide on categories

**Comment by carbon-hvze** [comment]
can we list a couple of errors that do not make sense? 

I think we can agree on the structure and cover them with schemas..

**Comment by carbon-hvze** [comment]
#28 is related to the developer's need to understand how to fix a validation error when :path, :schema are provided
